"""item model refactory

Revision ID: 4aae637182ff
Revises: 9c253ddc12be
Create Date: 2026-03-09 21:34:53.314819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aae637182ff'
down_revision = '9c253ddc12be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('expiration_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiration_date', sa.DATE(), nullable=True))

    # ### end Alembic commands ###
