"""novas colunas em request

Revision ID: 95318bc8e167
Revises: 4aae637182ff
Create Date: 2026-03-31 08:51:28.836267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95318bc8e167'
down_revision = '4aae637182ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rejected_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('canceled_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_column('canceled_at')
        batch_op.drop_column('rejected_at')

    # ### end Alembic commands ###
