"""relationship user

Revision ID: 9c253ddc12be
Revises: 3e36951bd59c
Create Date: 2026-03-09 16:36:40.659311

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9c253ddc12be'
down_revision = '3e36951bd59c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_by_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('requests_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['approved_by_id'], ['id'])
        batch_op.drop_column('approved_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_by', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('requests_ibfk_1'), 'users', ['approved_by'], ['id'])
        batch_op.drop_column('approved_by_id')

    # ### end Alembic commands ###
