"""novas colunas em item

Revision ID: ec3e147cc7ed
Revises: b28955b607f2
Create Date: 2026-03-31 10:46:14.410359

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ec3e147cc7ed'
down_revision = 'b28955b607f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_total', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('stock_reserved', sa.Integer(), nullable=True))
        batch_op.drop_column('stock')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('stock_reserved')
        batch_op.drop_column('stock_total')

    # ### end Alembic commands ###
